## Podstawy

Import numpy

In [2]:
import numpy as np

Tworzenie tablicy

In [4]:
[1, 2, 3, 4, 5] * 2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [3]:
tab1 = np.array([1, 2, 3, 4, 5])

In [ ]:
tab1

Pomnozenie kazdego elementu 

In [ ]:
tab1 * 2

Pozostale operacje

In [ ]:
tab1 - 2

Dodanie dwóch tablic

In [ ]:
tab1 + tab1

Mnozenie

In [ ]:
tab1 * tab1

Operacja gdy inne rozmiary

In [ ]:
np.array([1, 2]) * tab1

In [ ]:
np.array([1, 2]) * np.array([[1], [2]])

In [ ]:
np.array([[1], [2]]) * np.array([1, 2])

In [ ]:
np.array([1, 2, 3]) @ np.array([[1], [4], [8]])

In [ ]:
np.array([1, 2, 3]).dot(np.array([[1], [4], [8]]))

In [ ]:
np.array([[1, 2, 3]]).transpose().dot(np.array([[1, 4, 8]]))

### Sumowanie

In [ ]:
np.array([1, 2, 3]).sum()

In [ ]:
np.sum(np.array([1, 2, 3]))

In [ ]:
np.sum(np.array([[1, 2, 3], [4, 5, 6]]))

In [ ]:
np.array([[1, 2, 3], [4, 5, 6]]).sum(0) 

In [ ]:
np.array([[1, 2, 3], [4, 5, 6]]).sum(1)

### Srednia

In [ ]:
np.array([[1, 2, 3], [4, 5, 6]]).mean()

In [ ]:
np.array([[1, 2, 3], [4, 5, 6]]).mean(0)


In [ ]:
np.array([[1, 2, 3], [4, 5, 6]]).mean(1)

### Odchylenie

In [ ]:
np.array([[1, 2, 3], [4, 5, 6]]).std()

In [ ]:
np.array([[1, 2, 3], [4, 5, 6]]).std(0)

In [ ]:
np.array([[1, 2, 3], [4, 5, 6]]).std(1)


## Generowanie tablic

In [ ]:
np.arange(10)

In [ ]:
np.full((3, 3), True, dtype=bool)

In [ ]:
np.full((3, 3), 2, dtype=int)

In [ ]:
np.ones((3,3), dtype=int)

In [ ]:
np.diag([1, 2, 3])

In [ ]:
np.diag([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
np.random.rand(2)

In [ ]:
np.random.rand(2, 2, 3)

https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.random.html

## Sortowanie

In [5]:
tab = np.random.randint(0, 10, 10)
print(tab)
print(tab.sort())
print(tab)
print(np.flip(tab))
tab.sort()

[0 4 2 4 1 3 5 6 6 2]
None
[0 1 2 2 3 4 4 5 6 6]
[6 6 5 4 4 3 2 2 1 0]


In [ ]:
tab2 = np.array([
    [1, "A"],
    [3, "B"],
    [5, "D"],
    [2, "C"]
    ])

tab2 = tab2[np.argsort(tab2[:,0])]
print(tab2)

## Pobierania elementów

In [ ]:
tab2 = np.arange(10)
tab2

In [ ]:
tab2[0]

In [ ]:
tab2[-1]

In [ ]:
tab2[9]

In [ ]:
tab2[1:3]

In [ ]:
np.arange(100)[0:40:3]

In [ ]:
[0:10:2]

In [ ]:
tab2[-1:5:1]

## Odwracanie

In [ ]:
np.flip(tab2)

In [ ]:
tab2[::-1]

In [ ]:
tab2.reshape((2, 5))

In [ ]:
tab2.reshape((5, 2))

## Filtrowanie

In [ ]:
tab3 = np.arange(10)
print(tab3)
print(tab3 % 2 == 0)
tab3[tab3 % 2 == 0]

In [ ]:
np.where(tab3 % 2 == 0)

## Wczytywanie danych

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

In [ ]:
iris[:,4]

In [ ]:
np.save("iris", iris[0:10])

In [ ]:
def convert(row):
    print(row)
    if row[4] == b'Iris-setosa':
        return 0
    if row[4] == b'Iris-versicolor':
        return 1
    else:
        return 2

In [ ]:
for row in iris:
    c = convert(row)
    row[4] = c
iris

## Zapis danych

In [ ]:
np.savetxt("iris.csv", iris.astype('float64'), fmt='%f, %f, %f, %f, %d')
